# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

workspace '../Freewoc'

target 'iWoc' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iWoc
  pod 'Firebase'

  target 'iWocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iWocUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
