# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

workspace '../Freewoc'

target 'Macwoc' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Macwoc
  pod 'FirebaseOSX'

  target 'MacwocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MacwocUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
